### ISSUE TITLE
typo: scnarios -> scenarios

### ISSUE THREAD

**Issue by rzmk** [simonhyll/tauri-by-simon#2]
https://tauri.by.simon.hyll.nu/best_practices/the_simon_process/

https://github.com/simonhyll/tauri-by-simon/blob/400a5b8e98b0678736e692a11ef589aead736864/src/content/docs/best_practices/the_simon_process.mdx#L52

![IMG_0286](https://github.com/simonhyll/tauri-by-simon/assets/30333942/b98e4a7a-cb91-408a-afd5-3eb638b7875e)

**Comment by simonhyll** [comment]
Nice catch, fixing it right away! 🤗
